name: Newman Run

on:
  pull_request:
    branches:
    - master
  workflow_dispatch:
    inputs:
      newman:
        description: 'Run'
        required: false
        default: 'Run action'

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: postman/collections/Lifepack API_50302f0b-3e83-4879-b099-b60ed8de4162.json
          environment: postman/environments/lifepack-mock.json
